name: WildCrops
version: '${version}'
main: me.monoto.customseeds.WildCrops
api-version: '1.20'
description: Wild Crops
authors:
  - Monoto

loader: me.monoto.customseeds.WildCropsLoader

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    SuperiorSkyblock2:
      load: BEFORE
      required: false
      join-classpath: true
    mcMMO:
      load: BEFORE
      required: false
      join-classpath: true
    GlobalStats:
      load: BEFORE
      required: false
      join-classpath: true
